services:
  techgrowthfwcapi:
    image: ghcr.io/valentinesamuel/techgrowthfwcapi:latest
    restart: unless-stopped
    env_file: .env
    networks: [proxy]
    mem_limit: 512m
    cpus: "1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.techgrowthfwc.rule=Host(`techgrowthfwcapi.valentinesamuel.name.ng`)"
      - "traefik.http.routers.techgrowthfwc.entrypoints=websecure"
      - "traefik.http.routers.techgrowthfwc.tls.certresolver=letsencrypt"
      - "traefik.http.services.techgrowthfwc.loadbalancer.server.port=3001"

networks:
  proxy:
    external: true
